### PR TITLE
support qa multiarch

### PR DESCRIPTION
**Pull request by purelind**
* some repo support multiarch image: tidb / pd / tikv

### CODE REVIEW

**Comment by purelind** [comment]
test ci example
1. release-5.4 not multi-arch  https://cd.pingcap.net/blue/organizations/jenkins/debug-pipeline1/detail/debug-pipeline1/115/pipeline
2. master with multi-arch https://cd.pingcap.net/blue/organizations/jenkins/debug-pipeline1/detail/debug-pipeline1/116/pipeline

**Review by dianqihanwangzi — APPROVED** [review]
lgtm

**Pull request merged**
